using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CameraMovement : MonoBehaviour
{
    public GameObject player;
    public Vector3 offset;
    // Start is called before the first frame update
    void Start()
    {
        offset = transform.position - player.transform.position;
    }

    // Update is called once per frame
    void LateUpdate()
    {

        Vector3 desiredPosition = player.transform.position + offset;
        desiredPosition.x = 1;
        desiredPosition.y = -5;
        transform.position  = desiredPosition;
    }
}
